### ISSUE TITLE
cannot reproduce example

### ISSUE THREAD

**Issue by marczz** [jsonberry/metalsmith-hbs-relative-partial#7]
After many try that failed, I try to reproduce your example, so I copied the directory structure the main template src/index.hbs and the partial src/about/components heading.hbs. I wrote an index.js like this

```js
var Metalsmith = require('metalsmith');
var partials = require('metalsmith-hbs-relative-partial');
var inplace = require('metalsmith-in-place');

Metalsmith(__dirname)
    .source('./src')
    .destination('./build')
    .use(partials({
        dirName: 'components'
    }))
    .use(inplace())
    .build(function (err) {
        // For error handling
        if (err) {
            throw err;
        }
    });
```

and when I execute this code with node v8.9.3 I get

```
$ node index.js

/home/marc/metaltest/index.js:15
            throw err;
            ^
Error: The partial about/heading could not be found
    at Object.invokePartial (/home/marc/metaltest/node_modules/jstransformer-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:281:11)
    at Object.invokePartialWrapper [as invokePartial] (/home/marc/metaltest/node_modules/jstransformer-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    at Object.eval [as main] (eval at createFunctionContext (/home/marc/metaltest/node_modules/jstransformer-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at main (/home/marc/metaltest/node_modules/jstransformer-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at Object.ret (/home/marc/metaltest/node_modules/jstransformer-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at Object.ret [as fn] (/home/marc/metaltest/node_modules/jstransformer-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at Transformer.render (/home/marc/metaltest/node_modules/metalsmith-in-place/node_modules/jstransformer/index.js:289:25)
    at resolve (/home/marc/metaltest/node_modules/metalsmith-in-place/lib/index.js:60:33)
    at new Promise (<anonymous>)
    at render (/home/marc/metaltest/node_modules/metalsmith-in-place/lib/index.js:29:10)
```

The versions of package I use is

```json
  "dependencies": {
    "jstransformer-handlebars": "^1.1.0",
    "metalsmith": "^2.3.0",
    "metalsmith-in-place": "^4.1.1",
    "metalsmith-jstransformer": "^0.13.0"
  }
```

You say that this plugin is aimed to be used with metalsmith-in-place, which has had a major change with version 2.0 the 2017-01-01, when it adopted jstransformer. As your plugin is from march 2017, I have assumed it rely on metalsmith-in-place greater than 2.0, but as there is presently no test data, and so metalsmith-in-place is not in your package.json, there is no way (except go through the code!) to know the targeted version.

What about this error, in which context your example is working?

**Comment by jsonberry** [comment]
@marczz hey thanks for making the issue! I'll put some eyes on this and get back to you. I think I can take some time this weekend to do so 👍

**Comment by jsonberry** [comment]
@marczz This package clearly could use some love, but it does appear to be working correctly.

Here's the `src` architecture I setup: 
```bash
src
    |about
        |components
            | heading.hbs
    | index.hbs
| index.hbs
```

The source of both `index.hbs` files:
```handlebars
{{> about/heading }}
```

Check it out:
<img width="937" alt="screen shot 2018-03-04 at 12 19 02 pm" src="https://user-images.githubusercontent.com/3082536/36950140-77c5fda6-1fa6-11e8-9dd9-49a2616b94cc.png">
I went back and made sure to include the about/heading.hbs partial in both the about page, and the main index, and it showed up in both index.html files in the build, and those aren't in the screenshot.

I did a build by running `node index.js`
# index.js
```javascript
const relativePartial = require('metalsmith-hbs-relative-partial');
const inPlace = require('metalsmith-in-place');
const ignoreGlobs = require('metalsmith-ignore')

require('metalsmith')(__dirname)
  .source('./src') // source directory
  .destination('./build') // destination directory
  .use(
    relativePartial({
      dirName: 'components'
    })
  )
  .use(inPlace())
  .use(ignoreGlobs(['**/components/*']))
  .build(function(err) {
    // build process
    if (err) throw err; // error handling is required
  });
```

# metalsmith.json
```json
{
  "plugins": {
    "metalsmith-hbs-relative-partial": {
      "dirName": "components"
    }
  }
}
```
# package.json
```json
{
  "dependencies": {
    "jstransformer-handlebars": "^1.1.0",
    "metalsmith": "^2.3.0",
    "metalsmith-hbs-relative-partial": "^1.0.4",
    "metalsmith-ignore": "^0.1.2",
    "metalsmith-in-place": "^4.1.1"
  }
}
```

It worked correctly with and without the `metalsmith.json` configuration.

The package could use some updates:
 - overview of codebase
 - tests
 - add deps to package.json
 - add a working example 
 - add info about needing to add `jstransformer-handlebars`

Do you see any big differences between my test setup and yours?

**Comment by marczz** [comment]
Dear @jsonberry I tried to reproduce your example and I still get:

```
Error: The partial about/heading could not be found
    at Object.invokePartial (/home/marc/metalsmith/metaltest2/node_modules/jstransformer-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:281:11)
```
Either I have down an error in copying your example, or we are working with an incompatible version of Node. (I told before I use v8.9.3)

I have put  in  [metaltest2.zip](https://github.com/jsonberry/metalsmith-hbs-relative-partial/files/1799511/metaltest2.zip) my usecase directory (except the node_modules that are recreated with `npm install`)  please diff it with your own example.
If there is no difference I don't see why it is not reproduced.
